### PR TITLE
Heroku Support

### PR DESCRIPTION
**Pull request by pokurt**

### CODE REVIEW

**Comment by athphane** [comment]
@pokurt aite give me a min to review.

**Comment by pokurt** [comment]
what if.. m o n g o

**Comment by pokurt** [comment]
wait.. will scientist see this?

**Comment by athphane** [comment]
its a public repo lol. and we have github notifications go to our HQ

**Comment by pokurt** [comment]
also pep fixx the generator please my ide didnt do well on this

**Comment by pokurt** [comment]
pep8 oof

**Pull request merged**
